name: Build

on:
    push:
        paths:
            - 'src/**'
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 18.x
              uses: actions/setup-node@v2
              with:
                  node-version: '18'
                  cache: 'npm'

            - name: Installing dependencies
              run: npm install

            - name: Building
              run: npm run build

            - name: Generate Coverage using Raw Jest
              run: npx jest --coverage --coverageProvider=v8 --json --testLocationInResults --outputFile="coverage/report.json"

            - uses: Otanikotani/jest-coverage-report-action@v1.2
              name: Jest Coverage Report with baseline
              with:
                coverage-file: coverage/report.json
                base-coverage-file: coverage/report.json

